
services:

  postgres-devjob:
    image: postgres:15-alpine
    container_name: postgres-devjob
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: devjob
    volumes:
      - devjob_data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
    networks:
      - devjob_backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s


  redis:
    image: redis:6.2-alpine
    container_name: redis-devjob
    hostname: redis-devjob
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=123456
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    command: redis-server --requirepass 123456
    networks:
      - devjob_backend


  spring-devjob:
    container_name: spring-devjob
    image: lean2708/spring-devjob:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - devjob_backend
    depends_on:
      postgres-devjob:
        condition: service_healthy

networks:
  devjob_backend:
    driver: bridge

volumes:
  devjob_data:
    driver: local
