

services:
  mysql-devjob:
    image: mysql:8.0.41-debian
    container_name: mysql-devjob
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: devjob
    volumes:
      - devjob_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
    networks:
      - devjob_backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s


  redis:
    image: redis:6.2-alpine
    container_name: redis-devjob
    hostname: redis-devjob
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=123456
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - devjob_backend


  spring-devjob:
    container_name: spring-devjob
    image: lean2708/spring-devjob:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - devjob_backend
    depends_on:
      mysql-devjob:
        condition: service_healthy

networks:
  devjob_backend:
    driver: bridge

volumes:
  devjob_data:
    driver: local
