server:
  port: 8080
  servlet:
    context-path: /devjob

spring:
  application:
    name: Spring_DevJob
  profiles:
    active: @spring.profiles.active@



app:
  resume:
    interview:
      days: 5

  forgot-password:
    verification-code:
      expiration-minutes: 5

  recover-account:
    verification-code:
      expiration-minutes: 10

