server:
  port: 8080
  servlet:
    context-path: /devjob

spring:
  application:
    name: Spring_DevJob
  profiles:
    active: dev

app:
  resume:
    interview:
      days: 5
  convert:
    days: 30