server:
  port: 8080
  servlet:
    context-path: /devjob

spring:
  application:
    name: Spring_DevJob
  profiles:
    active: @spring.profiles.active@

  # Max Size Upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  resume:
    interview:
      days: 5

  forgot-password:
    verification-code:
      expiration-minutes: 5

  recover-account:
    verification-code:
      expiration-minutes: 10

